### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
for your app's [listing at F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7904) – see #3.

### CODE REVIEW

**Comment by IzzySoft** [comment]
@tuyafeng any chance to get this PR merged – and have a new tag then covering it, so we can process your listing at F-Droid?

**Comment by proletarius101** [comment]
I think the author is busy dealing with deadlines. It's the end of the year after all :)

**Comment by tuyafeng** [comment]
Thanks 😀😀

**Comment by IzzySoft** [comment]
Thanks! Will you let us know once the next version is tagged? As F-Droid builds from the tag, that's also where it takes Fastlane from – so we'll need a tag to go on with the listing.

(Speaking of which: once your app is listed on F-Droid, do you want me to keep it in my repo nevertheless? Usually, at that point I remove it from mine unless explicitly requested otherwise. Some details on the pros and cons [can be found here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ).

**Comment by tuyafeng** [comment]
Sorry for the late reply, I will update the version information synchronously later.  At the same time, if the software exists in fdroid, it can be removed from the lzzy repository.

**Comment by IzzySoft** [comment]
Thanks! Marked the latter. Please let us know when the former is ready.

**Pull request merged**
